version: "3"
services:
  db:
    image: mongo
    restart: always
    ports: 28017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bqapi
    networks:
      - public
      - private
  node:
    image: node:12 # https://hub.docker.com/_/node/
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: mongodb://root:bqapi@db:27017/root?authSource=admin
      JWT_SECRET: xxxxxxxx
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: adminbq
    volumes:
      - ./:/home/node/app # montamos el codigo en el HOME del usuario _node_
    expose:
      - 8080 # nuestra app corre en el puerto 8080
    ports:
      # mapeamos el puerto 8080 de nuestro contenedor al puerto 80 de nuestra
      # máquina
      - 80:8080
    # reinstalamos las dependencias y levantamos el servidor
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - db
    networks:
      - public
      - private
networks:
  public:
    internal: false
  private:
    internal: true